#!/usr/bin/env sh

DIR="$(readlink -f "$(dirname "$0")")"
cd "$DIR/days" || exit 1
DAYS_DONE="$(find . -name "day*.st" | sort | tail -1 | sed -E 's/[^0-9]//g')"

for i in $(seq "$DAYS_DONE"); do
    DAYP="$(printf "%02d" "$i")"
    echo ": |> ./fetch.sh $i |> input/day$DAYP.txt"
done
